#!/bin/bash

echo -e "\n"
echo "Presetting sales org config for KH."

updateSalesorgconfigMutationReq=$(curl --location 'https://uat.ezrx.com/api/strapiEngineMutation' \
--header 'Content-Type: application/json' \
--data '{"query":"mutation updateSalesorgconfigMutation($input: UpdateSalesOrgConfigInput!) {           updateSalesOrgConfig(input: $input) {             salesOrgConfig {               salesOrgCode               ponRequired               priceOverride               expiryDateDisplay               enableBatchNumber               currency               netPriceOverride               languageFilter               enableVat               enableZDP5               languageValue               materialWithoutPrice               enableZDP8Override               displayOrderDiscount               enableIRN               enableTaxClassification               disableBundles               disableProcessingStatus               enableCollectiveNumber               enableGimmickMaterial               hideStockDisplay               showPOAttachment               disableDeliveryDate               enableTaxAtTotalLevelOnly               enableGreenDelivery               greenDeliveryDelayInDays               greenDeliveryUserRole               minOrderAmount               hideCustomer               disableOrderType               vatValue               enableSpecialInstructions               enableReferenceNote               enableMobileNumber               enablePaymentTerms               enableGMC               enableListPrice               enableDefaultMD               disablePaymentTermsDisplay               enableBillTo               enableOHPrice               addOosMaterials               oosValue               enableRemarks               enableTaxDisplay               enableGMN                }           }         }       ","variables":{"input":{"where":{"id":53},"data":{"salesOrgCode":"1500","ponRequired":true,"priceOverride":false,"expiryDateDisplay":true,"batchNumDisplay":true,"enableBatchNumber":false,"currency":"usd","netPriceOverride":false,"languageFilter":false,"enableVat":false,"enableZDP5":false,"languageValue":"","materialWithoutPrice":false,"enableZDP8Override":true,"displayOrderDiscount":true,"enableIRN":false,"enableTaxClassification":false,"disableBundles":false,"disableProcessingStatus":true,"enableCollectiveNumber":false,"enableGimmickMaterial":false,"hideStockDisplay":true,"showPOAttachment":false,"disableDeliveryDate":false,"enableTaxAtTotalLevelOnly":false,"enableGreenDelivery":false,"greenDeliveryDelayInDays":0,"greenDeliveryUserRole":0,"minOrderAmount":"20","hideCustomer":false,"disableOrderType":true,"vatValue":0,"enableSpecialInstructions":true,"enableReferenceNote":false,"enableMobileNumber":true,"enablePaymentTerms":false,"enableGMC":false,"enableListPrice":true,"enableDefaultMD":true,"disablePaymentTermsDisplay":true,"enableBillTo":true,"enableOHPrice":true,"addOosMaterials":false,"oosValue":0,"enableRemarks":true,"enableTaxDisplay":true,"enableGMN":true}}}}' )

response=$(echo $updateSalesorgconfigMutationReq)
echo "Response is : "  $response

echo "Your KH sales org config has been successfully reset."
echo -e "\n"