import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

import '../../core/common.dart';
import '../../robots/account_settings_robot.dart';
import '../../robots/orders/cart_robot.dart';
import '../../robots/home/customer_search_robot.dart';
import '../../robots/favorite_robot.dart';
import '../../robots/home/home_robot.dart';
import '../../robots/login_robot.dart';
import '../../robots/orders/create_order/material_list/material_detail_robot.dart';
import '../../robots/orders/create_order/material_list/material_list_robot.dart';
import '../../robots/orders/create_order/order_confirmation_robot.dart';
import '../../robots/history/order_history_details_robot.dart';
import '../../robots/history/order_history_robot.dart';
import '../../robots/orders/order_template/order_template_detail_robot.dart';
import '../../robots/orders/order_template/order_template_list_robot.dart';
import '../../robots/orders/saved_order/saved_order_detail_robot.dart';
import '../../robots/orders/saved_order/saved_order_list_robot.dart';
import '../../robots/home/ship_to_search_robot.dart';
import '../../robots/orders/create_order/order_summary_robot.dart';

void main() {
  late LoginRobot loginRobot;
  late HomeRobot homeRobot;
  late AccountSettingsRobot accountSettingsRobot;
  late CustomerSearchRobot customerSearchRobot;
  late ShipToSearchRobot shipToSearchRobot;
  late MaterialListRobot materialListRobot;
  late MaterialDetailRobot materialDetailRobot;
  late CartRobot cartRobot;
  late OrderSummaryRobot orderSummaryRobot;
  late OrderConfirmationRobot orderConfirmationRobot;
  late OrderHistoryRobot orderHistoryRobot;
  late OrderHistoryDetailsRobot orderHistoryDetailsRobot;
  late SavedOrderListRobot savedOrderListRobot;
  late SavedOrderDetailRobot savedOrderDetailRobot;
  late FavoriteRobot favoriteRobot;
  late OrderTemplateListRobot orderTemplateListRobot;
  late OrderTemplateDetailRobot orderTemplateDetailRobot;

  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  testWidgets('E2E Client User (TW Market) - Order', (tester) async {
    //initialize neccessary robots
    loginRobot = LoginRobot(tester);
    homeRobot = HomeRobot(tester);
    accountSettingsRobot = AccountSettingsRobot(tester);
    customerSearchRobot = CustomerSearchRobot(tester);
    shipToSearchRobot = ShipToSearchRobot(tester);
    materialListRobot = MaterialListRobot(tester);
    materialDetailRobot = MaterialDetailRobot(tester);
    cartRobot = CartRobot(tester);
    orderSummaryRobot = OrderSummaryRobot(tester);
    orderConfirmationRobot = OrderConfirmationRobot(tester);
    orderHistoryRobot = OrderHistoryRobot(tester);
    orderHistoryDetailsRobot = OrderHistoryDetailsRobot(tester);
    savedOrderListRobot = SavedOrderListRobot(tester);
    savedOrderDetailRobot = SavedOrderDetailRobot(tester);
    favoriteRobot = FavoriteRobot(tester);
    orderTemplateListRobot = OrderTemplateListRobot(tester);
    orderTemplateDetailRobot = OrderTemplateDetailRobot(tester);

    //init app
    await runAppForTesting(tester);

    await loginRobot.login('twclientuser', 'St@ysafe01');
    homeRobot.findAnnouncementCloseIcon();
    await homeRobot.closeAnnouncement();
    homeRobot.findSalesOrgSelector();
    await homeRobot.tapSalesOrgSelector();
    await homeRobot.selectSalesOrg('2800');
    homeRobot.findCustomerCodeSelector();
    await homeRobot.tapCustomerCodeSelector();
    customerSearchRobot.verify();
    await customerSearchRobot.search('30038539');
    await customerSearchRobot.tapCustomerCode('0030038539');
    homeRobot.verify();
    homeRobot.findShipToSelector();
    await homeRobot.tapShipToSelector();
    shipToSearchRobot.verify();
    await shipToSearchRobot.search('0095');
    await shipToSearchRobot.tapShipToCode(shipToCode: '0070100095');
    homeRobot.verify();
    await homeRobot.goToCreateOrder();
    materialListRobot.verify();
    await materialListRobot.search('451');
    materialListRobot.verifyEnableListPrice('000000000023168451');
    materialListRobot.verifyMaterialPrice();
    await materialListRobot.tapMaterial('000000000023168451');
    materialDetailRobot.verify();
    materialDetailRobot.findAddToCart();
    await materialDetailRobot.tapAddToCart();
    materialListRobot.verify();
    materialListRobot.findCartButton();
    await materialListRobot.tapCartButton();
    cartRobot.verify();
    cartRobot.findMaterialItem('000000000023168451', 1);
    cartRobot.findAddQuantity('000000000023168451');
    await cartRobot.tapAddQuantity('000000000023168451');
    cartRobot.findMaterialItem('000000000023168451', 2);

    cartRobot.verifyTotal('TWD', '0.00');
    cartRobot.findOrderSummary();
    await cartRobot.tapOrderSummary();
    orderSummaryRobot.verifyCustomerEmail('NA');
    //bug here, id comes in as 0070100095
    //await orderSummaryRobot.verifyShipToID('0070100095');
    orderSummaryRobot.verifySoldToID('0030038539');
    orderSummaryRobot.findContinueButton(0);
    await orderSummaryRobot.tapContinueButton(0);
    orderSummaryRobot.verifySoldToID('0030038539');
    orderSummaryRobot.verifyCountry('NTW');
    orderSummaryRobot.verifyPhone('035943248');
    orderSummaryRobot.verifyPostalCode('31010');
    orderSummaryRobot.findContinueButton(1);
    await orderSummaryRobot.tapContinueButton(1);
    orderSummaryRobot.verifyShipToID('0070100095');
    orderSummaryRobot.verifyCountry('NTW');
    orderSummaryRobot.verifyPhone('035943248');
    orderSummaryRobot.verifyPostalCode('31000');
    orderSummaryRobot.findContinueButton(2);
    await orderSummaryRobot.tapContinueButton(2);
    await orderSummaryRobot.enterContactPerson('1234');
    orderSummaryRobot.findSelectPaymentTerm();
    await orderSummaryRobot.tapSelectPaymentTerm();
    await orderSummaryRobot.tapPaymentTerm();
    orderSummaryRobot.findContinueButton(3);
    await orderSummaryRobot.tapContinueButton(3);
    orderSummaryRobot.verifyTotals('TWD', '0.00');
    orderSummaryRobot.findMaterialItem('000000000023168451', 2);
    orderSummaryRobot.findAddQuantity('000000000023168451');
    await orderSummaryRobot.tapAddQuantity('000000000023168451');
    orderSummaryRobot.findMaterialItem('000000000023168451', 3);
    orderSummaryRobot.verifyMaterialListPrice(false, 'TWD', '0.00');
    orderSummaryRobot.verifyMaterialUnitPrice(false, 'TWD', '0.00');
    orderSummaryRobot.verifyMaterialTotalPrice(false, 'TWD', '0.00');
    orderSummaryRobot.findSave();
    orderSummaryRobot.findSubmit();
    await orderSummaryRobot.tapSubmit();
    orderConfirmationRobot.verify();
    orderConfirmationRobot.findTitle();
    orderConfirmationRobot.findDescription();
    orderConfirmationRobot.findCreateNewOrderButton();
    orderConfirmationRobot.findGoToOrderHistoryButton();
    await orderConfirmationRobot.tapGoToOrderHistoryButton();
    orderHistoryRobot.verify();
    orderHistoryRobot.findOrderedItem();
    orderHistoryRobot.verifyOrderType('ZPOR');
    orderHistoryRobot.verifyMaterialID('23168451');
    orderHistoryRobot.verifyMaterialName('Reag Cup');
    orderHistoryRobot.verifyQuantity('3');
    await orderHistoryRobot.tapOrderedItem();
    orderHistoryDetailsRobot.verify();
    orderHistoryDetailsRobot.findOrderDetails();
    orderHistoryDetailsRobot.verifyOrderType('ZPOR');
    orderHistoryDetailsRobot.verifyContactPerson('1234');
    orderHistoryDetailsRobot.verifyContactNumber('035943248');
    orderHistoryDetailsRobot.verifyPaymentTerm('NA');
    await orderHistoryDetailsRobot.tapOrderDetails();
    orderHistoryDetailsRobot.findSoldToAddress();
    orderHistoryDetailsRobot.verifySoldToID('0030038539');
    orderHistoryDetailsRobot.verifyPostalCode('31010');
    orderHistoryDetailsRobot.verifyCountry('NTW');
    orderHistoryDetailsRobot.verifyPhone('035943248');
    await orderHistoryDetailsRobot.tapSoldToAddress();
    orderHistoryDetailsRobot.findShipToAddress();
    orderHistoryDetailsRobot.verifyShipToID('0070100095');
    orderHistoryDetailsRobot.verifyPostalCode('31000');
    orderHistoryDetailsRobot.verifyCountry('NTW');
    orderHistoryDetailsRobot.verifyPhone('035943248');
    await orderHistoryDetailsRobot.tapShipToAddress();
    orderHistoryDetailsRobot.findInvoices();
    orderHistoryDetailsRobot.findOrderSummary();
    orderHistoryDetailsRobot.verifyMaterialType('Comm');
    orderHistoryDetailsRobot.verifyMaterialID('23168451');
    orderHistoryDetailsRobot.verifyQuantity('3');
    orderHistoryDetailsRobot.verifyEnableZPPrice('000000000023168451');
    orderHistoryDetailsRobot.verifyEnableTotalPrice('000000000021022175');
    orderHistoryDetailsRobot.verifyOrderSummaryTax('0.00');
    await orderHistoryDetailsRobot.tapOrderSummary();
    orderHistoryDetailsRobot.findBackButton();
    await orderHistoryDetailsRobot.tapBackButton();
    orderHistoryRobot.verify();
    await homeRobot.tapHomeTab();
    homeRobot.verify();
    await homeRobot.goToCreateOrder();
    materialListRobot.verify();
    materialListRobot.verifyMaterialPrice();
    await materialListRobot.tapMaterial('000000000023168451');
    materialDetailRobot.verify();
    materialDetailRobot.findAddToCart();
    await materialDetailRobot.tapAddToCart();
    materialListRobot.verify();
    materialListRobot.findCartButton();
    await materialListRobot.tapCartButton();
    cartRobot.verify();
    cartRobot.findMaterialItem('000000000023168451', 1);
    cartRobot.findOrderSummary();
    await cartRobot.tapOrderSummary();
    orderSummaryRobot.findContinueButton(0);
    await orderSummaryRobot.tapContinueButton(0);
    orderSummaryRobot.findContinueButton(1);
    await orderSummaryRobot.tapContinueButton(1);
    orderSummaryRobot.findContinueButton(2);
    await orderSummaryRobot.tapContinueButton(2);
    await orderSummaryRobot.enterContactPerson('4444');
    orderSummaryRobot.findSelectPaymentTerm();
    await orderSummaryRobot.tapSelectPaymentTerm();
    await orderSummaryRobot.tapPaymentTerm();
    orderSummaryRobot.findContinueButton(3);
    await orderSummaryRobot.tapContinueButton(3);
    orderSummaryRobot.findSave();
    await orderSummaryRobot.tapSave();
    savedOrderListRobot.verify();
    savedOrderListRobot.findOrder();
    savedOrderListRobot.verifySoldToID('0030038539');
    savedOrderListRobot.verifyShipToID('0070100095');
    savedOrderListRobot.verifyOrderValue('TWD', '0.00');
    await savedOrderListRobot.tapOrder();
    savedOrderDetailRobot.verify();
    savedOrderDetailRobot.verifyMaterialNumber('23168451');
    savedOrderDetailRobot.verifyMaterialQuantity('1');
    savedOrderDetailRobot.verifyUnitPrice('NA');
    savedOrderDetailRobot.findAddToCart();
    await savedOrderDetailRobot.tapAddToCart();
    cartRobot.verify();
    cartRobot.findOrderSummary();
    await cartRobot.tapOrderSummary();
    orderSummaryRobot.findContinueButton(0);
    await orderSummaryRobot.tapContinueButton(0);
    orderSummaryRobot.findContinueButton(1);
    await orderSummaryRobot.tapContinueButton(1);
    orderSummaryRobot.findContinueButton(2);
    await orderSummaryRobot.tapContinueButton(2);
    await orderSummaryRobot.enterContactPerson('4444');
    orderSummaryRobot.findSelectPaymentTerm();
    await orderSummaryRobot.tapSelectPaymentTerm();
    await orderSummaryRobot.tapPaymentTerm();
    orderSummaryRobot.findContinueButton(3);
    await orderSummaryRobot.tapContinueButton(3);
    orderSummaryRobot.findSubmit();
    await orderSummaryRobot.tapSubmit();
    orderConfirmationRobot.verify();
    orderConfirmationRobot.findGoToOrderHistoryButton();
    await orderConfirmationRobot.tapGoToOrderHistoryButton();
    orderHistoryRobot.verify();
    homeRobot.findHomeTab();
    await homeRobot.tapHomeTab();
    await homeRobot.goToCreateOrder();
    materialListRobot.findFavoriteIcon('23168451');
    await materialListRobot.tapFavoriteIcon('23168451');
    await materialListRobot.goBack();
    homeRobot.verify();
    homeRobot.findFavoriteTab();
    await homeRobot.tapFavoriteTab();
    favoriteRobot.verify();
    favoriteRobot.findFavoriteItem();
    favoriteRobot.verifyMaterialNumber('23168451');
    favoriteRobot.verifyUnitPrice('NA');
    favoriteRobot.findFavoriteIcon('000000000023168451');
    await favoriteRobot.tapFavoriteIcon('000000000023168451');
    homeRobot.findAccountTab();
    await homeRobot.tapAccountTab();
    accountSettingsRobot.findNoLoginOnBehalf();
    homeRobot.findHomeTab();
    await homeRobot.tapHomeTab();
    await homeRobot.goToCreateOrder();
    materialListRobot.verify();
    await materialListRobot.tapMaterial('000000000023168451');
    materialDetailRobot.verify();
    materialDetailRobot.findAddToCart();
    await materialDetailRobot.tapAddToCart();
    materialListRobot.verify();
    materialListRobot.findCartButton();
    await materialListRobot.tapCartButton();
    cartRobot.verify();
    cartRobot.findMaterialItem('000000000023168451', 1);
    cartRobot.findOrderSummary();
    await cartRobot.tapOrderSummary();
    orderSummaryRobot.findOrderTemplate();
    await orderSummaryRobot.tapOrderTemplate();
    orderSummaryRobot.findOrderTemplate();
    await orderSummaryRobot.enterTemplateName('template1');
    orderSummaryRobot.findTemplateSaveButton();
    await orderSummaryRobot.tapTemplateSaveButton();
    await orderSummaryRobot.goBack();
    await cartRobot.goBack();
    await materialListRobot.goBack();
    homeRobot.findOrderTemplate();
    await homeRobot.tapOrderTemplate();
    orderTemplateListRobot.findTemplateItem('template1');
    await orderTemplateListRobot.tapTemplateItem('template1');
    orderTemplateDetailRobot.verifyMaterialNumber('23168451');
    orderTemplateDetailRobot.verifyUnitPrice('NA');
    orderTemplateDetailRobot.verifyMaterialQuantity('1');
    orderTemplateDetailRobot.findAddToCart();
    await orderTemplateDetailRobot.tapAddToCart();
    cartRobot.verify();
    cartRobot.findOrderSummary();
    await cartRobot.tapOrderSummary();
    orderSummaryRobot.findContinueButton(0);
    await orderSummaryRobot.tapContinueButton(0);
    orderSummaryRobot.findContinueButton(1);
    await orderSummaryRobot.tapContinueButton(1);
    orderSummaryRobot.findContinueButton(2);
    await orderSummaryRobot.tapContinueButton(2);
    await orderSummaryRobot.enterContactPerson('4444');
    orderSummaryRobot.findSelectPaymentTerm();
    await orderSummaryRobot.tapSelectPaymentTerm();
    await orderSummaryRobot.tapPaymentTerm();
    orderSummaryRobot.findContinueButton(3);
    await orderSummaryRobot.tapContinueButton(3);
    orderSummaryRobot.findSubmit();
    await orderSummaryRobot.tapSubmit();
    orderConfirmationRobot.verify();
    orderConfirmationRobot.findGoToOrderHistoryButton();
    await orderConfirmationRobot.tapGoToOrderHistoryButton();
    orderHistoryRobot.verify();
    homeRobot.findHomeTab();
    await homeRobot.tapHomeTab();
    homeRobot.findOrderTemplate();
    await homeRobot.tapOrderTemplate();
    orderTemplateListRobot.findTemplateItemDelete();
    await orderTemplateListRobot.tapTemplateItemDelete();
    orderTemplateListRobot.verifyConfirmationDialog();
    orderTemplateListRobot.findConfirmButton();
    await orderTemplateListRobot.tapConfirmButton();
    await orderTemplateListRobot.goBack();
  });
}
