// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'invoice_item_dto.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_InvoiceItemDto _$$_InvoiceItemDtoFromJson(Map<String, dynamic> json) =>
    _$_InvoiceItemDto(
      companyCode: json['companyCode'] as String? ?? '',
      bpCustomerNumber: json['bpCustomerNumber'] as String? ?? '',
      accountingDocument: json['accountingDocument'] as String? ?? '',
      accountingDocumentType: json['accountingDocumentType'] as String? ?? '',
      fiscalYear: json['fiscalYear'] as String? ?? '',
      accountingDocumentItem: json['accountingDocumentItem'] as String? ?? '',
      specialGLCode: json['specialGLCode'] as String? ?? '',
      postingKey: json['postingKey'] as String? ?? '',
      postingKeyName: json['postingKeyName'] as String? ?? '',
      netDueDate: json['netDueDate'] as String? ?? '',
      postingDate: json['postingDate'] as String? ?? '',
      transactionCurrency: json['transactionCurrency'] as String? ?? '',
      billingDocument: json['billingDocument'] as String? ?? '',
      referenceDocumentNumber: json['referenceDocumentNumber'] as String? ?? '',
      payerParty: json['payerParty'] as String? ?? '',
      payerName1: json['payerName1'] as String? ?? '',
      dueCalculationBaseDate: json['dueCalculationBaseDate'] as String? ?? '',
      cashDiscount1DueDate: json['cashDiscount1DueDate'] as String? ?? '',
      cashDiscount2DueDate: json['cashDiscount2DueDate'] as String? ?? '',
      cashDiscount1Percent: json['cashDiscount1Percent'] as String? ?? '',
      cashDiscount2Percent: json['cashDiscount2Percent'] as String? ?? '',
      invoiceProcessingStatus: json['invoiceProcessingStatus'] as String? ?? '',
      documentReferenceID: json['documentReferenceID'] as String? ?? '',
      purchaseOrderByCustomer: json['purchaseOrderByCustomer'] as String? ?? '',
      customerReferenceNumber: json['customerReferenceNumber'] as String? ?? '',
      openAmountInTransCrcy: json['openAmountInTransCrcy'] as int? ?? 0,
      grossAmount: json['grossAmount'] as int? ?? 0,
      netAmount: json['netAmount'] as int? ?? 0,
      taxAmount: json['taxAmount'] as int? ?? 0,
      paymentAmount: json['paymentAmount'] as int? ?? 0,
      iban: json['iban'] as String? ?? '',
      bankAccountNumber: json['bankAccountNumber'] as String? ?? '',
      bankName: json['bankName'] as String? ?? '',
      memoLine: json['memoLine'] as String? ?? '',
      paymentCardType: json['paymentCardType'] as String? ?? '',
      paymentCardTypeName: json['paymentCardTypeName'] as String? ?? '',
      paymentCardNumber: json['paymentCardNumber'] as String? ?? '',
      paymentCardMaskedNumber: json['paymentCardMaskedNumber'] as String? ?? '',
      paymentCardHolderName: json['paymentCardHolderName'] as String? ?? '',
      debitCreditCode: json['debitCreditCode'] as String? ?? '',
      postingPeriod: json['postingPeriod'] as String? ?? '',
      clearingAccountingDocument:
          json['clearingAccountingDocument'] as String? ?? '',
      clearingDate: json['clearingDate'] as String? ?? '',
      documentDate: json['documentDate'] as String? ?? '',
      amountInTransactionCurrency:
          (json['amountInTransactionCurrency'] as num?)?.toDouble() ?? 0.0,
      isDisputed: json['isDisputed'] as String? ?? '',
      disputeCaseUUID: json['disputeCaseUUID'] as String? ?? '',
      disputeCaseStatus: json['disputeCaseStatus'] as String? ?? '',
      disputeCaseStatusName: json['disputeCaseStatusName'] as String? ?? '',
      invoiceReference: json['invoiceReference'] as String? ?? '',
      partnerFunctionIsPrintRelevant:
          json['partnerFunctionIsPrintRelevant'] as bool? ?? false,
      functionIsXMLRelevant: json['functionIsXMLRelevant'] as bool? ?? false,
      invoiceIsResidualForInference:
          json['invoiceIsResidualForInference'] as String? ?? '',
      returnId: json['returnId'] as String? ?? '',
      orderId: json['orderId'] as String? ?? '',
    );

Map<String, dynamic> _$$_InvoiceItemDtoToJson(_$_InvoiceItemDto instance) =>
    <String, dynamic>{
      'companyCode': instance.companyCode,
      'bpCustomerNumber': instance.bpCustomerNumber,
      'accountingDocument': instance.accountingDocument,
      'accountingDocumentType': instance.accountingDocumentType,
      'fiscalYear': instance.fiscalYear,
      'accountingDocumentItem': instance.accountingDocumentItem,
      'specialGLCode': instance.specialGLCode,
      'postingKey': instance.postingKey,
      'postingKeyName': instance.postingKeyName,
      'netDueDate': instance.netDueDate,
      'postingDate': instance.postingDate,
      'transactionCurrency': instance.transactionCurrency,
      'billingDocument': instance.billingDocument,
      'referenceDocumentNumber': instance.referenceDocumentNumber,
      'payerParty': instance.payerParty,
      'payerName1': instance.payerName1,
      'dueCalculationBaseDate': instance.dueCalculationBaseDate,
      'cashDiscount1DueDate': instance.cashDiscount1DueDate,
      'cashDiscount2DueDate': instance.cashDiscount2DueDate,
      'cashDiscount1Percent': instance.cashDiscount1Percent,
      'cashDiscount2Percent': instance.cashDiscount2Percent,
      'invoiceProcessingStatus': instance.invoiceProcessingStatus,
      'documentReferenceID': instance.documentReferenceID,
      'purchaseOrderByCustomer': instance.purchaseOrderByCustomer,
      'customerReferenceNumber': instance.customerReferenceNumber,
      'openAmountInTransCrcy': instance.openAmountInTransCrcy,
      'grossAmount': instance.grossAmount,
      'netAmount': instance.netAmount,
      'taxAmount': instance.taxAmount,
      'paymentAmount': instance.paymentAmount,
      'iban': instance.iban,
      'bankAccountNumber': instance.bankAccountNumber,
      'bankName': instance.bankName,
      'memoLine': instance.memoLine,
      'paymentCardType': instance.paymentCardType,
      'paymentCardTypeName': instance.paymentCardTypeName,
      'paymentCardNumber': instance.paymentCardNumber,
      'paymentCardMaskedNumber': instance.paymentCardMaskedNumber,
      'paymentCardHolderName': instance.paymentCardHolderName,
      'debitCreditCode': instance.debitCreditCode,
      'postingPeriod': instance.postingPeriod,
      'clearingAccountingDocument': instance.clearingAccountingDocument,
      'clearingDate': instance.clearingDate,
      'documentDate': instance.documentDate,
      'amountInTransactionCurrency': instance.amountInTransactionCurrency,
      'isDisputed': instance.isDisputed,
      'disputeCaseUUID': instance.disputeCaseUUID,
      'disputeCaseStatus': instance.disputeCaseStatus,
      'disputeCaseStatusName': instance.disputeCaseStatusName,
      'invoiceReference': instance.invoiceReference,
      'partnerFunctionIsPrintRelevant': instance.partnerFunctionIsPrintRelevant,
      'functionIsXMLRelevant': instance.functionIsXMLRelevant,
      'invoiceIsResidualForInference': instance.invoiceIsResidualForInference,
      'returnId': instance.returnId,
      'orderId': instance.orderId,
    };
