// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'sales_organisation_configs_dto.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_SalesOrganisationConfigsDto _$$_SalesOrganisationConfigsDtoFromJson(
        Map<String, dynamic> json) =>
    _$_SalesOrganisationConfigsDto(
      disableProcessingStatus: json['disableProcessingStatus'] as bool,
      currency: json['currency'] as String,
      hideCustomer: json['hideCustomer'] as bool? ?? false,
      enableGimmickMaterial: json['enableGimmickMaterial'] as bool? ?? false,
      languageFilter: json['languageFilter'] as bool? ?? false,
      languageValue: handleEmptyLanguageValue(json, 'languageValue') as String,
      disablePrincipals: json['disablePrincipals'] as bool? ?? false,
      principalList: const _PrincipalListConverter()
          .fromJson(json['principalList'] as Map<String, dynamic>),
      disableOrderType: json['disableOrderType'] as bool? ?? false,
      enableBatchNumber: json['enableBatchNumber'] as bool? ?? false,
      disableBundles: json['disableBundles'] as bool? ?? false,
      enableZDP5: json['enableZDP5'] as bool? ?? false,
      enableTaxClassification:
          json['enableTaxClassification'] as bool? ?? false,
      enableVat: json['enableVat'] as bool? ?? false,
      vatValue: json['vatValue'] as int? ?? 0,
      materialWithoutPrice: json['materialWithoutPrice'] as bool? ?? false,
      enableSpecialInstructions:
          json['enableSpecialInstructions'] as bool? ?? false,
      enableReferenceNote: json['enableReferenceNote'] as bool? ?? false,
      enableCollectiveNumber: json['enableCollectiveNumber'] as bool? ?? false,
      enableMobileNumber: json['enableMobileNumber'] as bool? ?? false,
      enableFutureDeliveryDay:
          json['enableFutureDeliveryDay'] as bool? ?? false,
      enablePaymentTerms: json['enablePaymentTerms'] as bool? ?? false,
      futureDeliveryDay: json['futureDeliveryDay'] as String? ?? '',
      enableGMC: json['enableGMC'] as bool? ?? false,
      enableListPrice: json['enableListPrice'] as bool? ?? false,
      enableDefaultMD: json['enableDefaultMD'] as bool? ?? false,
      priceOverride: json['priceOverride'] as bool? ?? false,
      disablePaymentTermsDisplay:
          json['disablePaymentTermsDisplay'] as bool? ?? false,
      disableDeliveryDate: json['disableDeliveryDate'] as bool? ?? false,
      enableBillTo: json['enableBillTo'] as bool? ?? false,
      showPOAttachment: json['showPOAttachment'] as bool? ?? false,
      expiryDateDisplay: json['expiryDateDisplay'] as bool? ?? false,
      hideStockDisplay: json['hideStockDisplay'] as bool? ?? false,
      addOosMaterials: json['addOosMaterials'] as bool? ?? false,
      oosValue: json['oosValue'] as int? ?? 0,
      enableRemarks: json['enableRemarks'] as bool? ?? false,
      enableOHPrice: json['enableOHPrice'] as bool? ?? true,
      poNumberRequired: json['ponRequired'] as bool? ?? false,
      enableIRN: json['enableIRN'] as bool? ?? false,
      enableTaxDisplay: json['enableTaxDisplay'] as bool? ?? false,
      enableTaxAtTotalLevelOnly:
          json['enableTaxAtTotalLevelOnly'] as bool? ?? false,
      netPriceOverride: json['netPriceOverride'] as bool? ?? false,
      batchNumDisplay: json['batchNumDisplay'] as bool? ?? false,
      displayOrderDiscount: json['displayOrderDiscount'] as bool? ?? false,
      minOrderAmount: json['minOrderAmount'] as String? ?? '0',
      salesOrg: json['salesOrgCode'] as String? ?? '0',
      enableZDP8Override: json['enableZDP8Override'] as bool? ?? false,
      disableReturnsAccessSR: json['disableReturnsAccessSR'] as bool? ?? false,
      disableReturnsAccess: json['disableReturnsAccess'] as bool? ?? false,
      enableGreenDelivery: json['enableGreenDelivery'] as bool? ?? false,
      greenDeliveryDelayInDays: json['greenDeliveryDelayInDays'] as int? ?? 2,
      enableComboDeals: json['enableComboDeals'] as bool? ?? false,
      greenDeliveryUserRole: json['greenDeliveryUserRole'] as int? ?? 0,
      comboDealsUserRole: json['comboDealsUserRole'] as int? ?? 0,
      enableGMN: json['enableGMN'] as bool? ?? false,
      displayItemTaxBreakdown:
          json['displayItemTaxBreakdown'] as bool? ?? false,
      displaySubtotalTaxBreakdown:
          json['displaySubtotalTaxBreakdown'] as bool? ?? false,
      disablePayment: json['disablePayment'] as bool? ?? false,
    );

Map<String, dynamic> _$$_SalesOrganisationConfigsDtoToJson(
        _$_SalesOrganisationConfigsDto instance) =>
    <String, dynamic>{
      'disableProcessingStatus': instance.disableProcessingStatus,
      'currency': instance.currency,
      'hideCustomer': instance.hideCustomer,
      'enableGimmickMaterial': instance.enableGimmickMaterial,
      'languageFilter': instance.languageFilter,
      'languageValue': instance.languageValue,
      'disablePrincipals': instance.disablePrincipals,
      'principalList':
          const _PrincipalListConverter().toJson(instance.principalList),
      'disableOrderType': instance.disableOrderType,
      'enableBatchNumber': instance.enableBatchNumber,
      'disableBundles': instance.disableBundles,
      'enableZDP5': instance.enableZDP5,
      'enableTaxClassification': instance.enableTaxClassification,
      'enableVat': instance.enableVat,
      'vatValue': instance.vatValue,
      'materialWithoutPrice': instance.materialWithoutPrice,
      'enableSpecialInstructions': instance.enableSpecialInstructions,
      'enableReferenceNote': instance.enableReferenceNote,
      'enableCollectiveNumber': instance.enableCollectiveNumber,
      'enableMobileNumber': instance.enableMobileNumber,
      'enableFutureDeliveryDay': instance.enableFutureDeliveryDay,
      'enablePaymentTerms': instance.enablePaymentTerms,
      'futureDeliveryDay': instance.futureDeliveryDay,
      'enableGMC': instance.enableGMC,
      'enableListPrice': instance.enableListPrice,
      'enableDefaultMD': instance.enableDefaultMD,
      'priceOverride': instance.priceOverride,
      'disablePaymentTermsDisplay': instance.disablePaymentTermsDisplay,
      'disableDeliveryDate': instance.disableDeliveryDate,
      'enableBillTo': instance.enableBillTo,
      'showPOAttachment': instance.showPOAttachment,
      'expiryDateDisplay': instance.expiryDateDisplay,
      'hideStockDisplay': instance.hideStockDisplay,
      'addOosMaterials': instance.addOosMaterials,
      'oosValue': instance.oosValue,
      'enableRemarks': instance.enableRemarks,
      'enableOHPrice': instance.enableOHPrice,
      'ponRequired': instance.poNumberRequired,
      'enableIRN': instance.enableIRN,
      'enableTaxDisplay': instance.enableTaxDisplay,
      'enableTaxAtTotalLevelOnly': instance.enableTaxAtTotalLevelOnly,
      'netPriceOverride': instance.netPriceOverride,
      'batchNumDisplay': instance.batchNumDisplay,
      'displayOrderDiscount': instance.displayOrderDiscount,
      'minOrderAmount': instance.minOrderAmount,
      'salesOrgCode': instance.salesOrg,
      'enableZDP8Override': instance.enableZDP8Override,
      'disableReturnsAccessSR': instance.disableReturnsAccessSR,
      'disableReturnsAccess': instance.disableReturnsAccess,
      'enableGreenDelivery': instance.enableGreenDelivery,
      'greenDeliveryDelayInDays': instance.greenDeliveryDelayInDays,
      'enableComboDeals': instance.enableComboDeals,
      'greenDeliveryUserRole': instance.greenDeliveryUserRole,
      'comboDealsUserRole': instance.comboDealsUserRole,
      'enableGMN': instance.enableGMN,
      'displayItemTaxBreakdown': instance.displayItemTaxBreakdown,
      'displaySubtotalTaxBreakdown': instance.displaySubtotalTaxBreakdown,
      'disablePayment': instance.disablePayment,
    };
