import 'package:freezed_annotation/freezed_annotation.dart';

part 'approver_return_request_information.freezed.dart';

@freezed
class ApproverReturnRequestInformation with _$ApproverReturnRequestInformation {
  factory ApproverReturnRequestInformation({
    required String invoiceNo,
    required String returnValue,
    required List<String> actionRequired,
    required String expiryDate,
    required String comment,
    required String salesDocument,
    required String exchangeOrder,
    required String refundCurrency,
    required String rejectReason,
    required String exchangeOrderNumber,
    required String docType,
    required String referenceDocument,
    required String division,
    required String purchaseMethod,
    required String usage,
    required String distributionChannel,
    required String approvalTimeStamp,
    required String createdTimeStamp,
    required String poDate,
    required String returnQuantity,
    required String unitPrice,
    required String totalPrice,
    required String billingItemNumber,
    required String salesDocumentItemNumber,
    required String materialNumber,
    required String materialDescription,
    required String batch,
    required String materialGroup,
    required List<String> imageUrl,
    required List<String> attachmentUrl,
    required String plant,
    required String storageLocation,
    required String highLevelItemCode,
    required String orderReason,
    required String priceDate,
    required String createdDate,
    required String overrideType,
    required String overrideValue,
    required String returnOrderText,
    required String returnOrderDesc,
    required String principal,
    required String bapiSalesDocNumber,
    required String eZRxNumber,
    required String bapiStatus,
    required String cnNumber,
    required String status,
    required String statusReason,
    required String priceOverride,
    required String remarks,
    required bool sendForDestruction,
    required bool quarantine,
    required bool returnToStock,
    required bool productRecall,
    required String returnType,
    required String returnTypeDesc,
    required String purchaseNumberCOverride,
    required String purchaseNumberC,
    required bool ppaHeld,
    required bool outsidePolicy,
    required List<String> attachments,
  }) = _ApproverReturnRequestInformation;
}
