import 'package:ezrxmobile/domain/returns/value/value_objects.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'return_summary_request_information_request_info.freezed.dart';

@freezed
class RequestInfo with _$RequestInfo {
  const RequestInfo._();

  const factory RequestInfo({
    required String invoiceNumber,
    required String returnValue,
    required List actionRequired,
    required String expiryDate,
    required String comment,
    required String salesDocument,
    required String exchangeOrder,
    required String refundCurrency,
    required String rejectReason,
    required String exchangeOrderNumber,
    required String docType,
    required String referenceDocument,
    required String division,
    required String purchaseMethod,
    required String usage,
    required String distributionChannel,
    required String approvalTimeStamp,
    required String createdTimeStamp,
    required String poDate,
    required String returnQuantity,
    required double unitPrice,
    required double totalPrice,
    required String billingItemNumber,
    required String salesDocumentItemNumber,
    required String materialNumber,
    required String materialDescription,
    required String batch,
    required String materialGroup,
    required List imageUrl,
    required List attachmentUrl,
    required String plant,
    required String storageLocation,
    required String highLevelItemCode,
    required String orderReason,
    required String priceDate,
    required String createdDate,
    required String overrideType,
    required String overrideValue,
    required String returnOrderText,
    required String returnOrderDesc,
    required String principal,
    required String bapiSalesDocNumber,
    required String eZRxNumber,
    required String bapiStatus,
    required String cnNumber,
    required ReturnSummaryStatus status,
    required String statusReason,
    required String priceOverride,
    required String remarks,
    required bool sendForDestruction,
    required bool returnToStock,
    required bool quarantine,
    required bool productRecall,
    required String returnType,
    required String returnTypeDesc,
    required String purchaseNumberCOverride,
    required String purchaseNumberC,
    required bool ppaHeld,
    required bool outsidePolicy,
  }) = _RequestInfo;

  factory RequestInfo.empty() => RequestInfo(
        invoiceNumber: '',
        returnValue: '',
        actionRequired: [],
        expiryDate: '',
        comment: '',
        salesDocument: '',
        exchangeOrder: '',
        refundCurrency: '',
        rejectReason: '',
        exchangeOrderNumber: '',
        docType: '',
        referenceDocument: '',
        division: '',
        purchaseMethod: '',
        usage: '',
        distributionChannel: '',
        approvalTimeStamp: '',
        createdTimeStamp: '',
        poDate: '',
        returnQuantity: '',
        unitPrice: 0.0,
        totalPrice: 0.0,
        billingItemNumber: '',
        salesDocumentItemNumber: '',
        materialNumber: '',
        materialDescription: '',
        batch: '',
        materialGroup: '',
        imageUrl: [],
        attachmentUrl: [],
        plant: '',
        storageLocation: '',
        highLevelItemCode: '',
        orderReason: '',
        priceDate: '',
        createdDate: '',
        overrideType: '',
        overrideValue: '',
        returnOrderText: '',
        returnOrderDesc: '',
        principal: '',
        bapiSalesDocNumber: '',
        eZRxNumber: '',
        bapiStatus: '',
        cnNumber: '',
        status: ReturnSummaryStatus(''),
        statusReason: '',
        priceOverride: '',
        remarks: '',
        sendForDestruction: false,
        returnToStock: false,
        quarantine: false,
        productRecall: false,
        returnType: '',
        returnTypeDesc: '',
        purchaseNumberCOverride: '',
        purchaseNumberC: '',
        ppaHeld: false,
        outsidePolicy: false,
      );
}
