class MixpanelEvents {
  static String loginSuccess = 'Login Success';
  static String loginFailure = 'Login Failure';
  static String bannerClick = 'Banner Click';
  static String bannerImpression = 'Banner Impression';
  static String shipToAddressSave = 'Ship To Address Save';
  static String salesOrgSave = 'Sales Org Save';
  static String customerCodeSave = 'Customer Code Save';
  static String savedOrder = 'Saved Orders';
  static String goToOrderSummary = 'Go To Order Summary';
  static String viewLicenseInfo = 'View License Info';
  static String uploadAttachment = 'Upload Attachment';
  static String addToCartSuccess = 'Add To Cart Success';
  static String addToCartFailed = 'Add To Cart Failed';
  static String productSearch = 'Product Search';
  static String clearCart = 'Clear Cart';
  static String addFromFavorite = 'Add From Favourite';
  static String addBonus = 'Add Bonus';
  static String submitOrder = 'Submit Order';
  static String orderSuccess = 'Order Success';
  static String orderFailed = 'Order Failed';
  static String saveOrder = 'Save Order';
  static String reOrder = 'Reorder';
  static String selectTemplate = 'Select Template';
  static String createOrderFromTemplate = 'Create Order From Template';
  static String pageViewVisited = 'Pageview Visited';
  static String thankYouToCreate = 'THANK YOU TO CREATE';
  static String thankYouToHistory = 'THANK YOU TO HISTORY';
}
