import 'package:ezrxmobile/domain/account/entities/sales_organisation_configs.dart';
import 'package:ezrxmobile/domain/account/entities/sales_organisation_configs_principal.dart';
import 'package:ezrxmobile/domain/account/value/value_objects.dart';
import 'package:ezrxmobile/domain/core/value/value_objects.dart';

//DO NOT MODIFY THIS FILE - This file contains sales org configs from PROD.
//https://zuelligpharma.atlassian.net/wiki/spaces/eZRxP/pages/281903463/Mobile+v3+Regression+Test

final fakeTHSalesOrgConfigs = SalesOrganisationConfigs.empty().copyWith(
  salesOrg: SalesOrg('2902'),
  poNumberRequired: PoNumberRequired(true),
  priceOverride: false,
  expiryDateDisplay: false,
  batchNumDisplay: false,
  currency: Currency('thb'),
  enableMobileNumber: false,
  enableRemarks: false,
  enableListPrice: false,
  enableTaxDisplay: false,
  addOosMaterials: OosMaterial(true),
  oosValue: OosValue(0),
  enableDefaultMD: false,
  enableZDP8Override: true,
  enableGMC: false,
  enableGMN: false,
  minOrderAmount: '100',
  vatValue: 0,
  netPriceOverride: false,
  enableFutureDeliveryDay: true,
  futureDeliveryDay: FutureDeliveryDay('7'),
  enablePaymentTerms: false,
  enableVat: false,
  enableZDP5: false,
  materialWithoutPrice: false,
  enableBatchNumber: false,
  enableOHPrice: true,
  enableSpecialInstructions: true,
  enableReferenceNote: true,
  displayOrderDiscount: false,
  enableIRN: false,
  enableTaxClassification: false,
  disablePrincipals: true,
  principalList: <SalesOrganisationConfigsPrincipal>[],
  disableBundles: false,
  disableProcessingStatus: false,
  disableOrderType: false,
  displayItemTaxBreakdown: false,
  displaySubtotalTaxBreakdown: false,
  enableCollectiveNumber: false,
  enableGimmickMaterial: false,
  hideCustomer: false,
  enableBillTo: true,
  disablePaymentTermsDisplay: false,
  disableReturnsAccess: false,
  disablePayment: false,
  disableReturnsAccessSR: false,
  hideStockDisplay: false,
  showPOAttachment: true,
  disableOverrideFieldSR: false,
  disableOverrideFieldCustomer: false,
  disableDeliveryDate: true,
  allowReturnsOutsidePolicy: true,
  enableTaxAtTotalLevelOnly: false,
  hideCredit: false,
  enablePOAttachmentRequired: false,
  enableComboDeals: false,
  comboDealsUserRole: ComboDealUserRole(0),
);
