import 'package:ezrxmobile/domain/account/entities/order_type.dart';
import 'package:ezrxmobile/domain/account/entities/sales_organisation_configs.dart';
import 'package:ezrxmobile/domain/account/entities/sales_organisation_configs_principal.dart';
import 'package:ezrxmobile/domain/account/value/value_objects.dart';
import 'package:ezrxmobile/domain/core/value/value_objects.dart';
import 'package:ezrxmobile/domain/order/value/value_objects.dart';

//DO NOT MODIFY THIS FILE - This file contains sales org configs from PROD.
//https://zuelligpharma.atlassian.net/wiki/spaces/eZRxP/pages/281903463/Mobile+v3+Regression+Test

final fakeHKSalesOrgConfigs = SalesOrganisationConfigs.empty().copyWith(
  salesOrg: SalesOrg('1700'),
  poNumberRequired: PoNumberRequired(false),
  priceOverride: true,
  expiryDateDisplay: true,
  batchNumDisplay: true,
  currency: Currency('hkd'),
  enableMobileNumber: true,
  enableRemarks: false,
  enableListPrice: false,
  enableTaxDisplay: false,
  addOosMaterials: OosMaterial(true),
  oosValue: OosValue(1),
  enableDefaultMD: false,
  enableZDP8Override: true,
  enableGMC: false,
  enableGMN: true,
  minOrderAmount: 300,
  vatValue: 0,
  netPriceOverride: false,
  enableFutureDeliveryDay: false,
  futureDeliveryDay: FutureDeliveryDay('7'),
  enablePaymentTerms: true,
  enableVat: false,
  enableZDP5: false,
  materialWithoutPrice: true,
  enableBatchNumber: false,
  enableOHPrice: true,
  enableSpecialInstructions: true,
  enableReferenceNote: true,
  displayOrderDiscount: false,
  enableIRN: false,
  enableTaxClassification: false,
  disablePrincipals: false,
  principalList: <SalesOrganisationConfigsPrincipal>[],
  disableBundles: true,
  disableProcessingStatus: false,
  disableOrderType: false,
  displayItemTaxBreakdown: false,
  displaySubtotalTaxBreakdown: false,
  enableCollectiveNumber: true,
  enableGimmickMaterial: true,
  hideCustomer: false,
  enableBillTo: true,
  disablePaymentTermsDisplay: false,
  disableReturnsAccess: false,
  disablePayment: false,
  disableReturnsAccessSR: false,
  hideStockDisplay: false,
  showPOAttachment: true,
  disableOverrideFieldSR: false,
  disableOverrideFieldCustomer: false,
  disableDeliveryDate: false,
  allowReturnsOutsidePolicy: false,
  enableTaxAtTotalLevelOnly: false,
  hideCredit: false,
  enablePOAttachmentRequired: false,
  enableComboDeals: false,
  comboDealsUserRole: ComboDealUserRole(0),
  enableMarketPlace: false,
  mpMinOrderAmount: 0.0,
  statementOfAccountEnabled: false,
  poReferenceLength: 35,
  referenceNoteLength: 132,
  enableDeliveryOptions: true,
  enableStandardDelivery: true,
  standardDeliveryDays: 5,
  enableRequestDeliveryDate: true,
  selectableDeliveryDays: 1,
  enableUrgentDelivery: true,
  enableTodayUrgentDelivery: true,
  todayDeliveryFee: 12,
  enableTomorrowUrgentDelivery: true,
  tomorrowDeliveryFee: 10,
  enableSaturdayUrgentDelivery: true,
  saturdayDeliveryFee: 5,
  orderTypes: [
    OrderType(
      categoryId: DocumentType('zpor'),
      orderType: StringValue('Regular Order (ZPOR)'),
      orderReason: -1,
      description: StringValue(''),
      enabled: true,
    ),
    OrderType(
      categoryId: DocumentType('zpfb'),
      orderType: StringValue('Sample order (ZPFB)'),
      orderReason: -1,
      description: StringValue(''),
      enabled: true,
    ),
    OrderType(
      categoryId: DocumentType('zpfc'),
      orderType: StringValue('FOC Order (ZPFC)'),
      orderReason: -1,
      description: StringValue(''),
      enabled: true,
    ),
  ],
);
