import 'package:ezrxmobile/domain/account/value/value_objects.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'update_sales_organisation_configs.freezed.dart';

@freezed
class UpdateSalesOrganisationConfigs with _$UpdateSalesOrganisationConfigs {
  const UpdateSalesOrganisationConfigs._();

  const factory UpdateSalesOrganisationConfigs({
    required SalesOrg salesOrg,
    required bool poNumberRequired,
    required bool priceOverride,
    required bool expiryDateDisplay,
    required bool batchNumDisplay,
    required bool enableBatchNumber,
    required Currency currency,
    required bool netPriceOverride,
    required bool enableVat,
    required bool enableZDP5,
    required bool materialWithoutPrice,
    required bool enableZDP8Override,
    required bool displayOrderDiscount,
    required bool enableIRN,
    required bool enableTaxClassification,
    required bool disableBundles,
    required bool disableProcessingStatus,
    required bool enableCollectiveNumber,
    required bool enableGimmickMaterial,
    required bool hideStockDisplay,
    required bool showPOAttachment,
    required bool disableDeliveryDate,
    required bool enableTaxAtTotalLevelOnly,
    required bool enableGreenDelivery,
    required int greenDeliveryDelayInDays,
    required GreenDeliveryUserRole greenDeliveryUserRole,
    required String minOrderAmount,
    required bool hideCustomer,
    required bool disableOrderType,
    required int vatValue,
    required bool enableSpecialInstructions,
    required bool enableReferenceNote,
    required bool enableMobileNumber,
    required bool enablePaymentTerms,
    required bool enableGMC,
    required bool enableListPrice,
    required bool enableDefaultMD,
    required bool disablePaymentTermsDisplay,
    required bool enableBillTo,
    required bool enableOHPrice,
    required bool addOosMaterials,
    required OosValue oosValue,
    required bool enableRemarks,
    required bool enableTaxDisplay,
    required bool enableGMN,
  }) = _UpdateSalesOrganisationConfigs;

  factory UpdateSalesOrganisationConfigs.empty() =>
      UpdateSalesOrganisationConfigs(
        salesOrg: SalesOrg(''),
        enableIRN: false,
        enableDefaultMD: false,
        disableProcessingStatus: false,
        batchNumDisplay: false,
        currency: Currency(''),
        hideCustomer: false,
        enableGimmickMaterial: false,
        disableOrderType: false,
        enableBatchNumber: false,
        disableBundles: false,
        enableZDP5: false,
        enableTaxClassification: false,
        enableVat: false,
        enableTaxAtTotalLevelOnly: false,
        vatValue: 0,
        materialWithoutPrice: false,
        enableSpecialInstructions: false,
        enableReferenceNote: false,
        enableCollectiveNumber: false,
        enableMobileNumber: false,
        enablePaymentTerms: false,
        enableGMC: false,
        enableListPrice: false,
        priceOverride: false,
        disablePaymentTermsDisplay: false,
        disableDeliveryDate: false,
        enableBillTo: false,
        showPOAttachment: false,
        hideStockDisplay: false,
        expiryDateDisplay: false,
        addOosMaterials: false,
        oosValue: OosValue(0),
        enableRemarks: false,
        enableOHPrice: true,
        poNumberRequired: false,
        enableTaxDisplay: false,
        netPriceOverride: false,
        displayOrderDiscount: false,
        minOrderAmount: '0',
        enableZDP8Override: false,
        enableGreenDelivery: false,
        greenDeliveryDelayInDays: 0,
        greenDeliveryUserRole: GreenDeliveryUserRole(0),
        enableGMN: false,
      );
}
