# Test all the test cases when commit happend
# 

trigger: none

resources:
- repo: self

jobs:
- job: Analyse
  pool: k8_agents_mobile
  displayName: Analyze flutter. Reject error, warning, info code
  steps: 
  - bash: flutter375 analyze --fatal-infos --fatal-warnings
  - bash: flutter375 pub run dart_code_metrics:metrics analyze lib --fatal-style --fatal-performance --fatal-warnings
- job:
  pool: k8_agents_mobile
  displayName: Test application
  steps: 
  - bash: flutter375 test test/application
- job:
  pool: k8_agents_mobile
  displayName: Test domain
  steps: 
  - bash: flutter375 test test/domain
- job:
  pool: k8_agents_mobile
  displayName: Test infrastructure -> account
  steps: 
  - bash: flutter375 test test/infrastructure/account
- job:
  pool: k8_agents_mobile
  displayName: Test infrastructure -> announcement
  steps: 
  - bash: flutter375 test test/infrastructure/announcement
- job:
  pool: k8_agents_mobile
  displayName: Test infrastructure -> aup_tc
  steps: 
  - bash: flutter375 test test/infrastructure/aup_tc
- job:
  pool: k8_agents_mobile
  displayName: Test infrastructure -> auth
  steps: 
  - bash: flutter375 test test/infrastructure/auth
- job:
  pool: k8_agents_mobile
  displayName: Test infrastructure -> banner
  steps: 
  - bash: flutter375 test test/infrastructure/banner
- job:
  pool: k8_agents_mobile
  displayName: Test infrastructure -> favourites
  steps: 
  - bash: flutter375 test test/infrastructure/favourites
- job:
  pool: k8_agents_mobile
  displayName: Test infrastructure -> order
  steps: 
  - bash: flutter375 test test/infrastructure/order
- job:
  pool: k8_agents_mobile
  displayName: Test infrastructure -> returns
  steps: 
  - bash: flutter375 test test/infrastructure/returns
- job:
  pool: k8_agents_mobile
  displayName: Test presentation -> account
  steps: 
  - bash: flutter375 test test/presentation/account
- job:
  pool: k8_agents_mobile
  displayName: Test presentation -> announcement
  steps: 
  - bash: flutter375 test test/presentation/announcement
- job:
  pool: k8_agents_mobile
  displayName: Test presentation -> aup_tc_test
  steps: 
  - bash: flutter375 test test/presentation/aup_tc_test
- job:
  pool: k8_agents_mobile
  displayName: Test presentation -> auth
  steps: 
  - bash: flutter375 test test/presentation/auth
- job:
  pool: k8_agents_mobile
  displayName: Test presentation -> favorites
  steps: 
  - bash: flutter375 test test/presentation/favorites
- job:
  pool: k8_agents_mobile
  displayName: Test presentation -> home
  steps: 
  - bash: flutter375 test test/presentation/home
- job:
  pool: k8_agents_mobile
  displayName: Test presentation -> order-history
  steps: 
  - bash: flutter375 test test/presentation/order_history
- job:
  pool: k8_agents_mobile
  displayName: Test presentation -> orders
  steps: 
  - bash: flutter375 test test/presentation/orders
- job:
  pool: k8_agents_mobile
  displayName: Test presentation -> returns
  steps: 
  - bash: flutter375 test test/presentation/returns