# Test all the test cases when commit happend
trigger: none

resources:
  - repo: self

pool: dnd-azdevops-flutter

variables:
  - group: "eZRx plus CICD"

jobs:
- job: FlutterVersion
  displayName: 'Version flutter'
  steps:
  - bash: flutter doctor -v

- job: FlutterAnalyze
  displayName: 'Analyze flutter'
  steps:
  - bash: flutter analyze --fatal-infos --fatal-warnings

- job: DCMVersion
  displayName: 'DCM Version'
  steps:
  - bash: dcm --version

- job: DCMAnalyse
  displayName: 'DCM Analyse'
  steps:
  - bash: dcm analyze lib --ci-key=$DCM_CI_KEY --email=$DCM_LICENSE_EMAIL --fatal-style --fatal-performance --fatal-warnings
    env:
      DCM_CI_KEY: '$(DCM_CI_KEY)'
      DCM_LICENSE_EMAIL: '$(DCM_LICENSE_EMAIL)'

- job: DCMCheckParameters
  displayName: 'DCM Check Parameters'
  steps:
  - bash: dcm check-parameters lib --ci-key=$DCM_CI_KEY --email=$DCM_LICENSE_EMAIL --fatal-found
    env:
      DCM_CI_KEY: '$(DCM_CI_KEY)'
      DCM_LICENSE_EMAIL: '$(DCM_LICENSE_EMAIL)'

- job: DCMCheckUnusedCode
  displayName: 'DCM Check Unused Code'
  steps:
  - bash: dcm check-unused-code lib --ci-key=$DCM_CI_KEY --email=$DCM_LICENSE_EMAIL --fatal-unused
    env:
      DCM_CI_KEY: '$(DCM_CI_KEY)'
      DCM_LICENSE_EMAIL: '$(DCM_LICENSE_EMAIL)'

- job: DCMCheckUnusedFiles
  displayName: 'DCM Check Unused Files'
  steps:
  - bash: dcm check-unused-files lib --ci-key=$DCM_CI_KEY --email=$DCM_LICENSE_EMAIL --fatal-unused
    env:
      DCM_CI_KEY: '$(DCM_CI_KEY)'
      DCM_LICENSE_EMAIL: '$(DCM_LICENSE_EMAIL)'
      
- job: DCMCheckDependencies
  displayName: 'DCM Check Dependencies'
  steps:
  - bash: dcm check-dependencies lib test integration_test --ignored-packages auto_route_generator,flutter_launcher_icons,flutter_native_splash,json_serializable,hive_generator,scandit_flutter_datacapture_core --ci-key=$DCM_CI_KEY --email=$DCM_LICENSE_EMAIL --fatal-found
    env:
      DCM_CI_KEY: '$(DCM_CI_KEY)'
      DCM_LICENSE_EMAIL: '$(DCM_LICENSE_EMAIL)'

- job: TestApplication
  displayName: Test application
  steps:
  - bash: flutter test test/application

- job: TestDomain
  displayName: Test domain
  steps:
  - bash: flutter test test/domain

- job: TestInfrastructureAccount
  displayName: Test infrastructure -> account
  steps:
  - bash: flutter test test/infrastructure/account

- job: TestInfrastructureAnnouncement
  displayName: Test infrastructure -> announcement
  steps:
  - bash: flutter test test/infrastructure/announcement

- job: TestInfrastructureAupTc
  displayName: Test infrastructure -> aup_tc
  steps:
  - bash: flutter test test/infrastructure/aup_tc

- job: TestInfrastructureAboutUs
  displayName: Test infrastructure -> about_us
  steps:
  - bash: flutter test test/infrastructure/about_us

- job: TestInfrastructureAnnouncementInfo
  displayName: Test infrastructure -> announcement_info
  steps:
  - bash: flutter test test/infrastructure/announcement_info

- job: TestInfrastructureArticle_info
  displayName: Test infrastructure -> article_info
  steps:
  - bash: flutter test test/infrastructure/article_info

- job: TestInfrastructureContactUs
  displayName: Test infrastructure -> contact_us
  steps:
  - bash: flutter test test/infrastructure/contact_us

- job: TestInfrastructureAuth
  displayName: Test infrastructure -> auth
  steps:
  - bash: flutter test test/infrastructure/auth

- job: TestInfrastructureBanner
  displayName: Test infrastructure -> banner
  steps:
  - bash: flutter test test/infrastructure/banner

- job: TestInfrastructurePayments
  displayName: Test infrastructure -> payments
  steps:
  - bash: flutter test test/infrastructure/payments

- job: TestInfrastructureOrder
  displayName: Test infrastructure -> order
  steps:
  - bash: flutter test test/infrastructure/order

- job: TestInfrastructureReturns
  displayName: Test infrastructure -> returns
  steps:
  - bash: flutter test test/infrastructure/returns

- job: TestInfrastructureChatbot
  displayName: Test infrastructure -> chatbot
  steps:
  - bash: flutter test test/infrastructure/chatbot

- job: TestInfrastructureCore
  displayName: Test infrastructure -> core
  steps:
  - bash: flutter test test/infrastructure/core

- job: TestInfrastructureNotification
  displayName: Test infrastructure -> notification
  steps:
  - bash: flutter test test/infrastructure/notification

- job: TestInfrastructureFaq
  displayName: Test infrastructure -> faq
  steps:
  - bash: flutter test test/infrastructure/faq

- job: TestInfrastructureDeepLinking
  displayName: Test infrastructure -> deep_linking
  steps:
  - bash: flutter test test/infrastructure/deep_linking

- job: TestPresentationAccount
  displayName: Test presentation -> account
  steps:
  - bash: flutter test test/presentation/account

- job: TestPresentationAnnouncement
  displayName: Test presentation -> announcement
  steps:
  - bash: flutter test test/presentation/announcement

- job: TestPresentationAupTc
  displayName: Test presentation -> aup_tc_test
  steps:
  - bash: flutter test test/presentation/aup_tc_test

- job: TestPresentationAuth
  displayName: Test presentation -> auth
  steps:
  - bash: flutter test test/presentation/auth

- job: TestPresentationHome
  displayName: Test presentation -> home
  steps:
  - bash: flutter test test/presentation/home

- job: TestPresentationIntro
  displayName: Test presentation -> intro
  steps:
  - bash: flutter test test/presentation/intro

- job: TestPresentationMore
  displayName: Test presentation -> more
  steps:
  - bash: flutter test test/presentation/more

- job: TestPresentationOrderHistory
  displayName: Test presentation -> order-history
  steps:
  - bash: flutter test test/presentation/order_history

- job: TestPresentationOrders
  displayName: Test presentation -> orders
  steps:
  - bash: flutter test test/presentation/orders

- job: TestPresentationReturns
  displayName: Test presentation -> returns
  steps:
  - bash: flutter test test/presentation/returns

- job: TestPresentationPayments
  displayName: Test presentation -> payments
  steps:
  - bash: flutter test test/presentation/payments

- job: TestPresentationProducts
  displayName: Test presentation -> products
  steps:
  - bash: flutter test test/presentation/products

- job: TestPresentationNotification
  displayName: Test presentation -> notification
  steps:
  - bash: flutter test test/presentation/notification

- job: TestPresentationFAQ
  displayName: Test presentation -> faq
  steps:
  - bash: flutter test test/presentation/faq

- job: TestPresentationCore
  displayName: Test presentation -> core
  steps:
  - bash: flutter test test/presentation/core
