trigger:
  tags:
    include:
    - test.uat.*

resources:
- repo: self

pool:
  vmImage: 'macos-12'

variables:
  - group: "eZRx Cred"

stages:
- stage: AndroidUATRegressionJob
  dependsOn: []
  displayName: AndroidUATRegressionJob
  jobs:

  - job: INTEGRATION_TESTs
    pool: 
      name: devops-flutter33
    displayName: INTEGRATION_TESTs
    steps: 

    - task: Bash@3
      displayName: Preset Sales Org Configs
      inputs:
        targetType: 'inline'
        script: |
          chmod 777 ./integration_test/kh/reset_sales_org_config.sh
          ./integration_test/kh/reset_sales_org_config.sh
          chmod 777 ./integration_test/mm/reset_sales_org_config.sh
          ./integration_test/mm/reset_sales_org_config.sh
          chmod 777 ./integration_test/my/reset_sales_org_config.sh
          ./integration_test/my/reset_sales_org_config.sh
          chmod 777 ./integration_test/ph/reset_sales_org_config.sh
          ./integration_test/ph/reset_sales_org_config.sh
          chmod 777 ./integration_test/sg/reset_sales_org_config.sh
          ./integration_test/sg/reset_sales_org_config.sh
          chmod 777 ./integration_test/th/reset_sales_org_config.sh
          ./integration_test/th/reset_sales_org_config.sh
          chmod 777 ./integration_test/tw/reset_sales_org_config.sh
          ./integration_test/tw/reset_sales_org_config.sh
          chmod 777 ./integration_test/vn/reset_sales_org_config.sh
          ./integration_test/vn/reset_sales_org_config.sh

    - task: Bash@3
      displayName: Run Integration tests
      inputs:
        targetType: 'inline'
        script: |
          export BROWSERSTACK_USERNAME='$(BROWSERSTACK_USERNAME)'
          export BROWSERSTACK_ACCESSKEY='$(BROWSERSTACK_ACCESSKEY)'
          export ENABLE_GEOLOCATION='$(ENABLE_GEOLOCATION)'
          chmod 777 run_intg_android_browserstack.sh
          testIT=("./integration_test/th/order/client_user.dart":"TH" "./integration_test/ph/order/client_user.dart":"PH" "./integration_test/mm/order/client_user.dart":"SG" "./integration_test/kh/order/client_user.dart":"KH" "./integration_test/vn/order/client_user.dart":"VN" "./integration_test/sg/order/client_user.dart":"SG" "./integration_test/my/order/client_user.dart":"MY" "./integration_test/tw/order/client_user.dart":"TW" "./integration_test/th/order/external_sales_rep.dart":"TH" "./integration_test/ph/order/external_sales_rep.dart":"PH" "./integration_test/mm/order/external_sales_rep.dart":"SG" "./integration_test/kh/order/external_sales_rep.dart":"KH" "./integration_test/vn/order/external_sales_rep.dart":"VN" "./integration_test/sg/order/external_sales_rep.dart":"SG" "./integration_test/my/order/external_sales_rep.dart":"MY" "./integration_test/tw/order/external_sales_rep.dart":"TW")
          ./run_intg_android_browserstack.sh ${testIT[@]}
